// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent(phrase string) Event {
	message := NewMessage(phrase)
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	return event
}
